// Generated by flutterfire configure — do not edit manually.
// Re-run `flutterfire configure` if you add new Firebase services.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Only Android is supported in MVP.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAObPqWQUulxk22j_7HKug_gGJ02Y0j0AI',
    appId: '1:828828836714:android:64336819e77689ede3fb13',
    messagingSenderId: '828828836714',
    projectId: 'agrokavach-34bf1',
    storageBucket: 'agrokavach-34bf1.firebasestorage.app',
  );
}
